### ISSUE TITLE
Auto creation of existing posts/resources not added as iMoneza Resources

### ISSUE THREAD

**Issue by KevinMZiegler** [iMoneza/wordpress-imoneza#14]
On the site: http://imoneza-dev-sandbox.cloudapp.net/coffee-magazine, iMoneza Lite was installed, then Pro on 4/5 and 4/6 respectively.  After upgrading to Pro, an indication that the eight pieces of content would be load in about a half hour.  After a couple of hours, the content still hasn't been loaded as resources on the property "Coffee Magazine".  A new post was added "Koffee is Kool", and this was added as a new resource, and the post "Latte Art 5" was updated to override the pricing group - this too was added as a resource.

**Comment by KevinMZiegler** [comment]
It may also be noteworthy to indicate that in the iMoneza settings, it now recognizes that only seven resources still need to be uploaded to iMoneza.  Before making the update to the Latte Art 5 post, this was shown as eight resources.

**Comment by aaronsaray** [comment]
I found this error and fixed it.  It will be fixed in the next deploy.  I'll update this ticket when it's ready to be tested again.
