### ISSUE TITLE
WP Pricing Group - blank

### ISSUE THREAD

**Issue by KevinMZiegler** [iMoneza/wordpress-imoneza#16]
Some resource, presumably resources that haven't yet been uploaded, contain a blank pricing group (empty).  See below:
![image](https://cloud.githubusercontent.com/assets/17073742/14329321/7dc56b5e-fc00-11e5-9d06-cc7ccc80d090.png)

**Comment by aaronsaray** [comment]
Figured out this was because they weren't updated yet - so it was filling in an empty value.  I've set this to be the default value - because that's what it will be.  This will go out with the next push to QA.
