### ISSUE TITLE
Fatal Error activating iMoneza plugin

### ISSUE THREAD

**Issue by KevinMZiegler** [iMoneza/wordpress-imoneza#5]
While logged in to http://imoneza-dev-sandbox.cloudapp.net/coffee-magazine as "kevin" on 4/13 approx 1:26pm, I clicked "Activate" on the iMoneza plugin (was already installed), nearly instantly, I received error: "plugin could not be activated because it triggered a fatal error"

"Fatal error: Class 'iMoneza\Library\WordPress\Base' not found in /www/coffee-magazine/wp-content/plugins/imoneza/src/App.php on line 16"

The plugin was not activated after this error occurred.  Trying a second time yielded the same result.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/17073742/14504792/e3b5b93e-017b-11e6-90b2-b176632ac292.png)

**Comment by aaronsaray** [comment]
This has been fixed and I verified it is no longer a problem.

This is because git had a cached submodule that I had to remove by hand (fun fact - there was no .gitmodules file - but somehow it was still there).
